### ISSUE TITLE
SpindleNet

### ISSUE THREAD

**Issue by punkyoon** [dzzp/argos-back#5]
# [SpindleNet](https://github.com/yokattame/SpindleNet)

- [3DPes](https://drive.google.com/file/d/0B56OfSrVI8hudTZNZmF3dUc0SWc/view?usp=sharing)
- [cuhk01](https://www.google.com/url?q=https://drive.google.com/file/d/0BxJeH3p7Ln48NjY1NmV4TUZKN2c/edit?usp%3Dsharing&sa=D&ust=1506743555869000&usg=AFQjCNHbNtl3bdtXZJ7ZSpZQEHVUqFadlQ)
- [cuhk02](https://drive.google.com/file/d/0B56OfSrVI8huM2w0ZHNOUXF2SWs/view?usp=sharing)
- [cuhk03](https://www.google.com/url?q=https://drive.google.com/file/d/0BxJeH3p7Ln48djNVVVJtUXh6bXc/edit?usp%3Dsharing&sa=D&ust=1506743488576000&usg=AFQjCNGemi9DN1vnw9GPxyeQfDp9cIenSA)
- [SenseReID](https://drive.google.com/file/d/0B56OfSrVI8hubVJLTzkwV2VaOWM/view?usp=sharing)
- [Shinpuhkan2014](https://drive.google.com/open?id=0B56OfSrVI8huRERDQ2JpMXBZcUk)
- [psdb](https://drive.google.com/open?id=0B56OfSrVI8huLUtkNU1tRjZkc3M)
- [i-LIDS](https://drive.google.com/open?id=0B56OfSrVI8huWDAxSnVJbXhiLUU)
- [Market-1501](https://drive.google.com/file/d/0B8-rUzbwVRk0cGtxWmFFVDZkNUE/view)
- [VIPeR](https://www.researchgate.net/profile/Douglas_Gray4/publication/261596035_Viewpoint_Invariant_Pedestrian_Recognition_VIPeR_Dataset_v10/data/02e7e534c1c7e926c6000000/VIPeRv10.zip)
- [PRID](https://files.icg.tugraz.at/f/6ab7e8ce8f/?raw=1)

SpindleNet에서 사용하는 코드는 `Python 2.7`에서 돌려야 한다......

**Comment by punkyoon** [comment]
## Download large file from google drive using python script

#### from_google_drive.py

```python
import requests

def download_file_from_google_drive(id, destination):
    def get_confirm_token(response):
        for key, value in list(response.cookies.items()):
            if key.startswith('download_warning'):
                return value

        return None

    def save_response_content(response, destination):
        CHUNK_SIZE = 32768

        with open(destination, "wb") as f:
            for chunk in response.iter_content(CHUNK_SIZE):
                if chunk: # filter out keep-alive new chunks
                    f.write(chunk)

    URL = "https://docs.google.com/uc?export=download"

    session = requests.Session()

    response = session.get(URL, params = { 'id' : id }, stream = True)
    token = get_confirm_token(response)

    if token:
        params = { 'id' : id, 'confirm' : token }
        response = session.get(URL, params = params, stream = True)
    save_response_content(response, destination)


if __name__ == "__main__":
    import sys
    if len(sys.argv) is not 3:
        print("Usage: python google_drive.py drive_file_id destination_file_path")
    else:
        # TAKE ID FROM SHAREABLE LINK
        file_id = sys.argv[1]
        # DESTINATION FILE ON YOUR DISK
        destination = sys.argv[2]
        download_file_from_google_drive(file_id, destination)
```

**Comment by punkyoon** [comment]
17.9.30 현재 `SpindleNet/data/format_cuhk03.py`에 심각한 문제가 발생하고 있다..

**Comment by punkyoon** [comment]
각 dataset의 폴더 이름

- cuhk01: cuhk01
- cuhk02: cuhk02
- cuhk03: cuhk03_release
- PRID: prid
- psdb: psdb
- VIPeR: VIPeR
- 3DPeS: 3DPeS
- Shinpuhkan: shinpuhkan
- SenseReID: SenseReID
- Market-1501: Market-1501-v15.09.15
- I-LIDS: ilids

**Comment by juice500ml** [comment]
https://github.com/rbgirshick/fast-rcnn
그냥 caffe를 빌드하면 안되고 저 브랜치에 있는걸 빌드해야하네요.

train_head.sh 부터 쭉 에러납니다! (https://github.com/rbgirshick/py-faster-rcnn/issues/579)

**Comment by punkyoon** [comment]
https://github.com/yokattame/caffe에 있는 것을 cmake로 build 하기..^^;;

**Comment by punkyoon** [comment]
protobuf 3.3.0 버전이 설치된 것을 확인했지만, 스크립트를 실행할 때마다 protobuf 2.5 버전이 설치되어 있다고 나오면서 에러가 발생중이다..

**Comment by punkyoon** [comment]
## SpindleNet Requirements

1. Python 2.7
2. [Custom Caffe](https://github.com/yokattame/caffe)
3. protobuf 2.5.0

> sudo pip2 install protobuf==2.5.0

4. opencv 3.3.0
